# Generated by Django 2.1.4 on 2018-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='nume_portas',
            new_name='numero_de_portas',
        ),
        migrations.RemoveField(
            model_name='acessorio',
            name='carro',
        ),
        migrations.AddField(
            model_name='carro',
            name='acessorio',
            field=models.ManyToManyField(to='store.Acessorio'),
        ),
        migrations.AddField(
            model_name='carro',
            name='data_do_anuncio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
