# Generated by Django 2.1.4 on 2018-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181209_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
