# Generated by Django 2.1.4 on 2018-12-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carro_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
