# Generated by Django 2.1.4 on 2018-12-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
    ]
