# Generated by Django 2.1.4 on 2018-12-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_venda_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='carro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='store.Carro'),
        ),
    ]
